### ISSUE TITLE
Pre-trained version of Epitome available

### ISSUE THREAD

**Issue by Al-Murphy** [YosefLab/epitome#92]
Hi,

Is there a pre-trained version of Epitome available for the model used to get the performance described in the paper? I would like to apply it to my own data without retraining.

Thanks,
Alan.

**Comment by akmorrow13** [comment]
Hi @Al-Murphy,

Attached is a model trained on the following cell typrs: `['Panc1', 'PC-9', 'OCI-LY7', 'MCF-7', 'Karpas-422', 'IMR-90', 'HepG2', 'HeLa-S3', 'HCT116', 'H9', 'H1', 'GM23338', 'GM23248', 'GM12878', 'A549']` Depending on the cell types you are evaluating, you can re-train and tailor this list to more similar ones.

This model was trained on the following histones `modifications:H3K9me3,H3K4me3,H3K4me1,H3K36me3,H3K27me3,H3K27ac`
I have attached a zip file containing the script for training and the model. 
[histone_model.tgz](https://github.com/YosefLab/epitome/files/9024242/histone_model.tgz)
